//! Win32 glue for the Quick Terminal (M5): a global-hotkey listener thread plus
//! the topmost / borderless window manipulation that gpui 0.2.2 doesn't expose.
//!
//! gpui's `WindowKind::PopUp` already gives us a borderless, no-taskbar window
//! (`WS_EX_TOOLWINDOW`), but not always-on-top and no programmatic move/show. We
//! reach past gpui via the raw HWND for exactly those: set `WS_EX_TOPMOST`, slide
//! the window with `SetWindowPos`, and pump a private message loop for a global
//! `RegisterHotKey`. All positioning is in **physical pixels** (what `SetWindowPos`
//! and `GetMonitorInfoW` speak), which is why the [`tn_config`] geometry is
//! unit-agnostic. Windows only; a no-op stub keeps non-Windows builds compiling.

#[cfg(target_os = "windows")]
mod imp {
    use std::ffi::c_void;
    use std::os::windows::ffi::OsStrExt;
    use std::sync::atomic::AtomicBool;

    use futures::channel::mpsc::{self, UnboundedReceiver, UnboundedSender};
    use tn_config::{HotkeySpec, Rect};
    use windows::Win32::Foundation::{HINSTANCE, HWND, LPARAM, LRESULT, POINT, WPARAM};
    use windows::Win32::Graphics::Gdi::{
        CreateRoundRectRgn, GetMonitorInfoW, MonitorFromWindow, SetWindowRgn, HRGN, MONITORINFO,
        MONITOR_DEFAULTTONEAREST,
    };
    use windows::Win32::System::LibraryLoader::GetModuleHandleW;
    use windows::Win32::UI::HiDpi::GetDpiForWindow;
    use windows::Win32::UI::Input::KeyboardAndMouse::{
        RegisterHotKey, HOT_KEY_MODIFIERS, MOD_ALT, MOD_CONTROL, MOD_NOREPEAT, MOD_SHIFT, MOD_WIN,
        VK_PROCESSKEY,
    };
    use windows::Win32::UI::Shell::{
        DefSubclassProc, SetWindowSubclass, Shell_NotifyIconW, NOTIFYICONDATAW,
        NOTIFY_ICON_DATA_FLAGS, NOTIFY_ICON_MESSAGE,
    };
    use windows::Win32::UI::WindowsAndMessaging::{
        AppendMenuW, CreatePopupMenu, CreateWindowExW, DefWindowProcW, DestroyMenu,
        DispatchMessageW, GetCursorPos, GetMessageW, GetWindowLongPtrW, LoadImageW, PostMessageW,
        PostQuitMessage, RegisterClassW, RegisterWindowMessageW, SendMessageW, SetForegroundWindow,
        SetWindowLongPtrW, SetWindowPos, ShowWindow, SystemParametersInfoW, TrackPopupMenu,
        TranslateMessage, CS_HREDRAW, CS_VREDRAW, GWLP_USERDATA, GWL_EXSTYLE, HICON, HWND_MESSAGE,
        HWND_TOPMOST, IMAGE_ICON, LR_LOADFROMFILE, MF_STRING, MSG, SPI_GETCLIENTAREAANIMATION,
        SWP_NOACTIVATE, SWP_NOMOVE, SWP_NOSIZE, SW_HIDE, SW_SHOW,
        SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS, TPM_BOTTOMALIGN, TPM_RETURNCMD, TPM_RIGHTBUTTON,
        WM_DESTROY, WM_HOTKEY, WM_KEYDOWN, WM_LBUTTONDBLCLK, WM_NULL, WM_RBUTTONUP, WM_SETICON,
        WNDCLASSW, WS_EX_TOPMOST,
    };

    fn as_hwnd(h: isize) -> HWND {
        HWND(h as *mut c_void)
    }

    // ── Application icon ────────────────────────────────────────────────────

    /// The Tn application icon (brand mark: gradient rounded square + terminal
    /// glyph). Generated by `scripts/gen_icon.py` — 4 sizes (16/32/48/256),
    /// BMP/DIB format (traditional ICO). Embedded in the binary.
    static ICON_BYTES: &[u8] = include_bytes!("../assets/tn.ico");

    /// Write the embedded ICO to a temp file once, then load it as an HICON
    /// at the requested size. Returns `HICON::default()` on failure (callers
    /// handle gracefully — a missing icon is cosmetic, not a crash).
    /// Write the embedded BMP ICO to a temp file and load it as an HICON at
    /// the requested size via `LoadImageW`. BMP/DIB format works on every
    /// Windows version back to XP — no PNG or `dwVersion` tricks needed.
    /// Returns `HICON::default()` on failure (null icon = harmless cosmetic loss).
    fn load_app_icon_at(cx: i32, cy: i32) -> HICON {
        // Write to %TEMP% — the file is ~285 KB. Re-written each call so an
        // app update gets the new icon without a stale cache.
        let tmp = std::env::temp_dir().join("Tn.AppIcon.ico");
        let _ = std::fs::write(&tmp, ICON_BYTES);

        let wide: Vec<u16> = tmp
            .as_os_str()
            .encode_wide()
            .chain(std::iter::once(0))
            .collect();
        unsafe {
            LoadImageW(
                Some(HINSTANCE::default()),
                windows::core::PCWSTR::from_raw(wide.as_ptr()),
                IMAGE_ICON,
                cx,
                cy,
                LR_LOADFROMFILE,
            )
        }
        .map(|h| HICON(h.0))
        .unwrap_or_default()
    }

    /// Set the taskbar / title-bar icon for a gpui window identified by its HWND.
    /// Sends `WM_SETICON` for both `ICON_SMALL` (title bar, 16×16) and `ICON_BIG`
    /// (taskbar / Alt-Tab, 48×48 — Windows scales down as needed).
    pub fn set_window_icon(hwnd: isize) {
        let h = as_hwnd(hwnd);
        let icon_small = load_app_icon_at(16, 16);
        let icon_big = load_app_icon_at(48, 48);
        unsafe {
            SendMessageW(
                h,
                WM_SETICON,
                Some(WPARAM(0)),
                Some(LPARAM(icon_small.0 as isize)),
            );
            SendMessageW(
                h,
                WM_SETICON,
                Some(WPARAM(1)),
                Some(LPARAM(icon_big.0 as isize)),
            );
        }
    }

    /// Translate a parsed hotkey to a Win32 (modifier mask, virtual-key) pair.
    /// `MOD_NOREPEAT` suppresses auto-repeat while the chord is held. Returns
    /// `None` for an unmappable key token.
    pub fn to_win32(spec: &HotkeySpec) -> Option<(HOT_KEY_MODIFIERS, u32)> {
        let mut mods = MOD_NOREPEAT;
        if spec.ctrl {
            mods |= MOD_CONTROL;
        }
        if spec.alt {
            mods |= MOD_ALT;
        }
        if spec.shift {
            mods |= MOD_SHIFT;
        }
        if spec.win {
            mods |= MOD_WIN;
        }
        Some((mods, vk_for(&spec.key)?))
    }

    /// Map a (lowercased) key token to a Windows virtual-key code.
    fn vk_for(key: &str) -> Option<u32> {
        let b = key.as_bytes();
        if b.len() == 1 {
            return match b[0] {
                c @ b'a'..=b'z' => Some((c - b'a' + 0x41) as u32), // VK_A..VK_Z
                c @ b'0'..=b'9' => Some(c as u32),                 // VK_0..VK_9
                b'`' => Some(0xC0),                                // VK_OEM_3
                b'-' => Some(0xBD),                                // VK_OEM_MINUS
                b'=' => Some(0xBB),                                // VK_OEM_PLUS
                _ => None,
            };
        }
        match key {
            "space" => Some(0x20),
            "tab" => Some(0x09),
            "enter" | "return" => Some(0x0D),
            "esc" | "escape" => Some(0x1B),
            "grave" | "backtick" => Some(0xC0),
            "minus" => Some(0xBD),
            f if f.starts_with('f') => {
                let n: u32 = f[1..].parse().ok()?;
                (1..=24).contains(&n).then_some(0x70 + (n - 1)) // VK_F1..VK_F24
            }
            _ => None,
        }
    }

    /// Spawn a dedicated thread that registers the global hotkey (`hwnd = None`,
    /// so `WM_HOTKEY` is posted to this thread's queue) and pumps its message
    /// loop, sending `()` on each press. Returns the receiver, or `None` if the
    /// key is unmappable. The OS unregisters the hotkey when the process exits.
    pub fn spawn_hotkey_listener(spec: &HotkeySpec) -> Option<UnboundedReceiver<()>> {
        let (mods, vk) = to_win32(spec)?;
        let (tx, rx) = mpsc::unbounded::<()>();
        std::thread::Builder::new()
            .name("tn-quick-hotkey".into())
            .spawn(move || unsafe {
                if RegisterHotKey(None, 1, mods, vk).is_err() {
                    return; // hotkey likely owned by another app
                }
                let mut msg = MSG::default();
                // GetMessageW: >0 normal, 0 on WM_QUIT, -1 on error.
                while GetMessageW(&mut msg, None, 0, 0).0 > 0 {
                    if msg.message == WM_HOTKEY && tx.unbounded_send(()).is_err() {
                        break; // receiver dropped — app is gone
                    }
                }
            })
            .ok();
        Some(rx)
    }

    /// Check whether we can register the Quick Terminal global hotkey. Spawns a
    /// short-lived thread that tries `RegisterHotKey` and exits (which unregisters
    /// the key). Returns `true` if we're the only instance that owns this hotkey
    /// (i.e. we can be the "primary" instance with tray + Quick Terminal).
    pub fn probe_hotkey(spec: &HotkeySpec) -> bool {
        let Some((mods, vk)) = to_win32(spec) else {
            return false;
        };
        let (tx, rx) = std::sync::mpsc::channel::<bool>();
        std::thread::Builder::new()
            .name("tn-hotkey-probe".into())
            .spawn(move || unsafe {
                let ok = RegisterHotKey(None, 1, mods, vk).is_ok();
                let _ = tx.send(ok);
                // Thread exits — the OS unregisters the hotkey. A tiny window
                // exists before the permanent listener re-registers, but another
                // process would need to start and probe in that exact instant.
                // We accept that (exceedingly rare) risk.
            })
            .ok();
        rx.recv_timeout(std::time::Duration::from_millis(500))
            .unwrap_or(false)
    }

    /// Make the window an always-on-top overlay (called once, on first reveal).
    /// gpui's PopUp is already borderless + off-taskbar; this adds topmost.
    pub fn make_topmost(h: isize) {
        let h = as_hwnd(h);
        unsafe {
            let ex = GetWindowLongPtrW(h, GWL_EXSTYLE);
            SetWindowLongPtrW(h, GWL_EXSTYLE, ex | WS_EX_TOPMOST.0 as isize);
            let _ = SetWindowPos(
                h,
                Some(HWND_TOPMOST),
                0,
                0,
                0,
                0,
                SWP_NOSIZE | SWP_NOMOVE | SWP_NOACTIVATE,
            );
        }
    }

    /// Move + resize the window (physical px), keeping it pinned topmost.
    pub fn set_bounds(h: isize, r: Rect) {
        unsafe {
            let _ = SetWindowPos(
                as_hwnd(h),
                Some(HWND_TOPMOST),
                r.x as i32,
                r.y as i32,
                r.width as i32,
                r.height as i32,
                SWP_NOACTIVATE,
            );
        }
    }

    /// Clip the window to a rounded rectangle (physical px size + corner radius), so a
    /// borderless **transparent** window reads as a clean rounded card instead of the
    /// OS's square window rectangle showing past the card's rounded corners. The gpui
    /// quad shader already rounds the card's fill, but the window itself is a sharp
    /// rectangle (Win10 doesn't round borderless windows), so its corners can peek;
    /// `SetWindowRgn` makes the *window shape* rounded to match. The system takes
    /// ownership of the region handle (do NOT delete it). Size-relative, so it survives
    /// the slide (which only moves the window); re-set it whenever the size changes.
    #[allow(dead_code)] // 幽灵窗改为卡片自绘顶垂形(SHEET 04);保留给未来窗形需要
    pub fn set_round_region(h: isize, w: f32, ht: f32, radius: f32) {
        unsafe {
            // CreateRoundRectRgn's right/bottom edges are exclusive → +1 to cover the
            // last column/row. Ellipse diameter = 2×radius.
            let d = (radius * 2.0).round() as i32;
            let rgn = CreateRoundRectRgn(0, 0, w as i32 + 1, ht as i32 + 1, d, d);
            if !rgn.is_invalid() {
                // redraw = true. System owns `rgn` after this; we don't free it.
                let _ = SetWindowRgn(as_hwnd(h), Some(rgn), true);
            }
        }
    }

    /// Drop any window region → back to a plain rectangle (a running session fills the
    /// drop-down edge-to-edge; only the launcher card wants rounding).
    #[allow(dead_code)] // 幽灵窗现走 set_ghost_region;保留给未来窗形需要
    pub fn clear_region(h: isize) {
        unsafe {
            let _ = SetWindowRgn(as_hwnd(h), None::<HRGN>, true);
        }
    }

    /// 顶垂形 region:上直角、下圆角(SHEET 04 幽灵窗形)。把圆角矩形向上平移
    /// 一个圆径,顶部两个圆角便落在窗外(region 以窗矩形裁剪),窗内只剩底部两
    /// 个圆角。窗体不透明(Windows/gpui 无逐像素透明,差异总结 §6 P0-2),圆角
    /// 外的像素被 region 裁掉 → 零白边。尺寸相关:resize 后需重设。
    pub fn set_ghost_region(h: isize, w: f32, ht: f32, radius: f32) {
        unsafe {
            let d = (radius * 2.0).round() as i32;
            // 右/下边界互斥 → +1 才盖住最后一行/列;顶边上移 d 拉直顶部。
            let rgn = CreateRoundRectRgn(0, -d, w as i32 + 1, ht as i32 + 1, d, d);
            if !rgn.is_invalid() {
                // redraw = true. System owns `rgn` after this; we don't free it.
                let _ = SetWindowRgn(as_hwnd(h), Some(rgn), true);
            }
        }
    }

    /// Show or hide the window. Showing also pulls it to the foreground so the
    /// user can type immediately (the hotkey press grants us foreground rights).
    pub fn show(h: isize, visible: bool) {
        let h = as_hwnd(h);
        unsafe {
            let _ = ShowWindow(h, if visible { SW_SHOW } else { SW_HIDE });
            if visible {
                let _ = SetForegroundWindow(h);
            }
        }
    }

    /// DPI scale factor (1.0 = 96 DPI / 100%) of the monitor the window sits on.
    /// `set_bounds`/`work_area` speak physical px, but gpui lays out content in
    /// **logical** px — so the launcher card (sized in logical px) must scale its
    /// window bounds up by this, or it clips on a HiDPI display. `GetDpiForWindow`
    /// (Win10 1607+) reads the window's per-monitor DPI directly, so it's right on
    /// the very first summon (no render needed) and tracks cross-monitor DPI.
    pub fn scale_for(h: isize) -> f32 {
        unsafe {
            match GetDpiForWindow(as_hwnd(h)) {
                0 => 1.0, // invalid window — assume 100%
                dpi => dpi as f32 / 96.0,
            }
        }
    }

    /// The work area (monitor minus taskbar, physical px) of the monitor the
    /// window currently sits on.
    pub fn work_area(h: isize) -> Option<Rect> {
        unsafe {
            let mon = MonitorFromWindow(as_hwnd(h), MONITOR_DEFAULTTONEAREST);
            let mut mi = MONITORINFO {
                cbSize: std::mem::size_of::<MONITORINFO>() as u32,
                ..Default::default()
            };
            if GetMonitorInfoW(mon, &mut mi).as_bool() {
                let w = mi.rcWork;
                Some(Rect::new(
                    w.left as f32,
                    w.top as f32,
                    (w.right - w.left) as f32,
                    (w.bottom - w.top) as f32,
                ))
            } else {
                None
            }
        }
    }

    /// Play the system default sound for a terminal bell (BEL / `\x07`), when the
    /// user opts into `[appearance].audio_bell`. `MessageBeep(MB_OK)` is async,
    /// non-blocking, and respects the user's sound scheme (silent if they muted
    /// the "Default Beep" event). See docs/产品体验/终端交互体验.md.
    pub fn system_beep() {
        use windows::Win32::System::Diagnostics::Debug::MessageBeep;
        use windows::Win32::UI::WindowsAndMessaging::MB_OK;
        unsafe {
            let _ = MessageBeep(MB_OK);
        }
    }

    pub fn reduced_motion_enabled() -> bool {
        let mut enabled = 1i32;
        let ok = unsafe {
            SystemParametersInfoW(
                SPI_GETCLIENTAREAANIMATION,
                0,
                Some((&mut enabled) as *mut _ as *mut std::ffi::c_void),
                SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS::default(),
            )
            .is_ok()
        };
        ok && enabled == 0
    }

    // ── IME key-routing fix (中文输入「输入法被限制」根治) ──────────────────────
    //
    // 病根在 gpui 0.2.2 的 Windows 文本输入走**旧的 IMM32** 而非 WT 用的 **TSF**:
    //   • gpui 判定「是否在合成」只看 `marked_text_range()`(= 应用的 marked text),
    //     而它仅在 IME 发 `GCS_COMPSTR` 时才被置位;**微软拼音等 TSF 原生输入法在
    //     IMM32 兼容层下从不发 `GCS_COMPSTR`**(自画候选窗、只在提交发 `GCS_RESULTSTR`)
    //     → gpui 的 `is_composing` **恒 false** → 它**从不把按键短路给 IME**,每个键都先
    //     派发到我们的 `on_key`(实证见 tn.log:`marked_text_range -> None`)。
    //   • gpui 只在**应用不消费该 keydown 时**才调 `translate_message` 把键交给 IME;且
    //     它的 `parse_char_message` 会**过滤掉控制字符**(退格 0x08/回车 0x0D/Esc 0x1B/Tab
    //     0x09 的 WM_CHAR 全被丢)→ 这些命名键既不能「放行」(WM_CHAR 被吞、键彻底丢失)、
    //     又必须在 `on_key` 里**编码送 PTY**(否则终端删不掉字)。结果:**合成期按退格/回车/
    //     方向键会被终端抢走**,无法删拼音、无法回车提交、无法翻候选页 = 用户感到的「受限」。
    //
    // 关键事实:**当 IME 正在处理某键(用户在合成)时,系统投递的 `WM_KEYDOWN` 其虚拟键
    // 是 `VK_PROCESSKEY`(0xE5)**。这是 OS 明确告诉我们「这个键属于 IME」。但 gpui 在
    // `handle_key_event` 里**悄悄用 `ImmGetVirtualKey` 还原出真实键**再派发给应用,所以到
    // `on_key` 这层已分不清「合成中的退格」和「终端用的退格」。
    //
    // 修法(无需 fork gpui,IME 无关):在 gpui 的 wndproc **之前**子类化窗口,凡 `WM_KEYDOWN`
    // 且 `wParam == VK_PROCESSKEY` 的键就是 IME 的——我们替它 `TranslateMessage`(驱动
    // `WM_IME_COMPOSITION` → gpui 的 `GCS_RESULTSTR` 提交链 → 我们的 `replace_text` 写 PTY)
    // 并**消费掉**(返回 0,不再下传 gpui),于是 gpui 永不会误编码它。IME **不**要的键以其
    // 真实虚拟键到达(非 VK_PROCESSKEY)→ 原样透传给 gpui → `on_key` 照常编码送终端。
    // 这样合成期的退格/回车/方向键/数字/空格全部回到 IME(删拼音、翻页、提交都正常)。
    //
    // 重入安全:子类回调在 gpui wndproc **之前**于消息派发链最前端运行,`TranslateMessage`
    // 只**投递** WM_IME_*/WM_CHAR 到队列(不同步回调 wndproc),且我们对 VK_PROCESSKEY
    // 直接 `return 0`(不调 `DefSubclassProc` → 不进 gpui wndproc)→ 不触碰 gpui 的 RefCell
    // 窗口状态,无 M5「外部调用重入借用」之忧。

    const TN_IME_SUBCLASS_ID: usize = 0x746E_0001; // "tn" + tag

    unsafe extern "system" fn ime_subclass_proc(
        hwnd: HWND,
        msg: u32,
        wparam: WPARAM,
        lparam: LPARAM,
        _uid_subclass: usize,
        _dwref_data: usize,
    ) -> LRESULT {
        if msg == WM_KEYDOWN {
            let vk = wparam.0 as u16; // virtual-key in the loword of wParam
            if vk == VK_PROCESSKEY.0 {
                // The IME owns this key (active composition). Route it to the IME and
                // CONSUME it so gpui's keydown handler never sees it (and so can't
                // mis-encode named keys like backspace/enter/arrows to the PTY).
                let m = MSG {
                    hwnd,
                    message: WM_KEYDOWN,
                    wParam: wparam,
                    lParam: lparam,
                    time: 0,
                    pt: POINT::default(),
                };
                let _ = TranslateMessage(&m);
                return LRESULT(0);
            }
        }
        DefSubclassProc(hwnd, msg, wparam, lparam)
    }

    /// Install the IME key-routing fix on a gpui window (see the note above). Must be
    /// called on the UI thread with a live HWND (e.g. the first `render` / window
    /// init). `SetWindowSubclass` is idempotent per (proc, id) — calling twice with
    /// the same id just refreshes it — and the OS removes the subclass on destroy,
    /// so no teardown is needed. Unlike `SetWindowPos`/`ShowWindow` it does NOT
    /// re-enter the window proc, so it is safe to call synchronously inside a gpui
    /// callback.
    pub fn install_ime_keyfix(h: isize) {
        unsafe {
            let _ = SetWindowSubclass(as_hwnd(h), Some(ime_subclass_proc), TN_IME_SUBCLASS_ID, 0);
        }
    }

    // ── IME enable / disable for ASCII-only input fields ─────────────────
    //
    // SSH Quick Connect 和类似只接受 ASCII 的输入框，打开时禁用 IME 合成，避免：
    //   ① 用户需要手动切英文才能输入；
    //   ② VK_PROCESSKEY 子类把 IME 合成键路由给 replace_text_in_range，
    //      而该输入框没有 EntityInputHandler，导致字符丢失。
    // `ImmAssociateContextEx(hwnd, NULL, 0)` = 解除窗口 IME 关联(禁用合成)；
    // `ImmAssociateContextEx(hwnd, NULL, IACE_DEFAULT)` = 恢复默认上下文。
    // 两者均作用于整个窗口，但在模态 overlay(scrim + 提示框)期间无副作用——
    // 底层终端已被 scrim 拦截。关闭 overlay 后立即恢复。

    pub fn set_ime_enabled(h: isize, enabled: bool) {
        use windows::Win32::UI::Input::Ime::{ImmAssociateContextEx, HIMC, IACE_DEFAULT};
        unsafe {
            let flags = if enabled { IACE_DEFAULT } else { 0 };
            let _ = ImmAssociateContextEx(as_hwnd(h), HIMC::default(), flags);
        }
    }

    // ── System tray + single-instance ──────────────────────────────────────
    //
    // When the main workspace window closes, the process stays alive (kept
    // running by the Quick Terminal's hidden PopUp window). A system-tray icon
    // gives the user a visible indication that Tn is still resident and a
    // right-click menu to restore the main window or quit entirely.
    //
    // Single-instance: a named mutex prevents a second `tn` process from
    // starting. Instead, the second instance signals the first (via a custom
    // window message to the tray message-only window) to restore the main
    // window and then exits immediately.

    /// Events from the tray icon message loop to the GPUI main thread.
    #[derive(Clone, Copy, Debug)]
    pub enum TrayEvent {
        /// User clicked "Show Tn" (double-click or context menu).
        Show,
        /// User clicked "Quit" in the tray context menu.
        Quit,
        /// Another instance asked us to show (via IPC message).
        ShowFromIpc,
    }

    /// Set to `true` when the user initiates a genuine quit (not close-to-tray).
    /// The `on_window_closed` handler checks this to decide: quit the process,
    /// or just hide to tray.
    pub static QUITTING: AtomicBool = AtomicBool::new(false);

    // Tray and IPC constants.
    const WM_TRAYICON: u32 = 0x8000 + 1; // WM_APP + 1
    const IDM_TRAY_SHOW: usize = 1001;
    const IDM_TRAY_QUIT: usize = 1002;
    const TRAY_ICON_UID: u32 = 1;
    #[allow(dead_code)]
    const TRAY_WINDOW_CLASS: &str = "Tn.TrayWindow";

    /// Per-window data hung off the tray message-only window via `GWLP_USERDATA`.
    struct TrayWindowData {
        tx: UnboundedSender<TrayEvent>,
        msg_show_main: u32, // registered window message for IPC
    }

    /// Window procedure for the hidden message-only tray window: handles tray
    /// icon callbacks (`WM_TRAYICON`) and IPC from a second `tn` instance.
    unsafe extern "system" fn tray_wndproc(
        hwnd: HWND,
        msg: u32,
        wparam: WPARAM,
        lparam: LPARAM,
    ) -> LRESULT {
        // Retrieve our TrayWindowData from GWLP_USERDATA.
        let ptr = GetWindowLongPtrW(hwnd, GWLP_USERDATA) as *mut TrayWindowData;
        if ptr.is_null() {
            return DefWindowProcW(hwnd, msg, wparam, lparam);
        }
        let data = &*ptr;

        if msg == WM_TRAYICON {
            let event = lparam.0 as u32;
            if event == WM_RBUTTONUP {
                // Right-click: show context menu.
                if let Some(ev) = show_tray_menu(hwnd) {
                    let _ = data.tx.unbounded_send(ev);
                }
            } else if event == WM_LBUTTONDBLCLK {
                // Double-click: restore main window.
                let _ = data.tx.unbounded_send(TrayEvent::Show);
            }
            return LRESULT(0);
        }

        // IPC: another instance posted our registered "show main" message.
        if msg == data.msg_show_main && data.msg_show_main != 0 {
            let _ = data.tx.unbounded_send(TrayEvent::ShowFromIpc);
            return LRESULT(0);
        }

        if msg == WM_DESTROY {
            // Free the TrayWindowData allocation.
            drop(Box::from_raw(ptr));
            SetWindowLongPtrW(hwnd, GWLP_USERDATA, 0);
            PostQuitMessage(0);
            return LRESULT(0);
        }

        DefWindowProcW(hwnd, msg, wparam, lparam)
    }

    /// Show the tray icon context menu at the cursor position. Returns the
    /// selected action, or `None` if the menu was dismissed without a selection.
    unsafe fn show_tray_menu(hwnd: HWND) -> Option<TrayEvent> {
        let menu = CreatePopupMenu().ok()?;
        let _ = AppendMenuW(menu, MF_STRING, IDM_TRAY_SHOW, windows::core::w!("显示 Tn"));
        let _ = AppendMenuW(menu, MF_STRING, IDM_TRAY_QUIT, windows::core::w!("退出"));

        let mut pt = POINT::default();
        GetCursorPos(&mut pt).ok()?;
        // `SetForegroundWindow` is required so that `TrackPopupMenu` dismisses
        // properly when the user clicks elsewhere.
        let _ = SetForegroundWindow(hwnd);

        let cmd = TrackPopupMenu(
            menu,
            TPM_RIGHTBUTTON | TPM_BOTTOMALIGN | TPM_RETURNCMD,
            pt.x,
            pt.y,
            Some(0),
            hwnd,
            None,
        );

        // Workaround: post a benign message so the menu definitely closes.
        let _ = PostMessageW(Some(hwnd), WM_NULL, WPARAM(0), LPARAM(0));
        let _ = DestroyMenu(menu);

        match cmd.0 as usize {
            IDM_TRAY_SHOW => Some(TrayEvent::Show),
            IDM_TRAY_QUIT => Some(TrayEvent::Quit),
            _ => None,
        }
    }

    // ── Tray icon create / remove ─────────────────────────────────────────

    /// Create the tray icon. `hwnd` must be the tray message-only window (the
    /// one receiving `WM_TRAYICON`). Uses the embedded Tn brand-mark icon
    /// (gradient rounded square + terminal glyph, same as the taskbar icon).
    /// Returns `true` on success.
    pub fn create_tray_icon(hwnd: isize) -> bool {
        let hwnd = as_hwnd(hwnd);
        let icon = load_app_icon_at(32, 32);
        let mut nid = NOTIFYICONDATAW::default();
        nid.cbSize = std::mem::size_of::<NOTIFYICONDATAW>() as u32;
        nid.hWnd = hwnd;
        nid.uID = TRAY_ICON_UID;
        nid.uFlags = NOTIFY_ICON_DATA_FLAGS(0x01 | 0x02 | 0x04); // NIF_MESSAGE | NIF_ICON | NIF_TIP
        nid.uCallbackMessage = WM_TRAYICON;
        nid.hIcon = icon;
        // Set the tooltip text: "Tn"
        let tip: Vec<u16> = "Tn\0".encode_utf16().collect();
        let len = tip.len().min(128);
        nid.szTip[..len].copy_from_slice(&tip[..len]);

        unsafe { Shell_NotifyIconW(NOTIFY_ICON_MESSAGE(0), &nid).as_bool() } // NIM_ADD = 0
    }

    /// Remove the tray icon. Call before quitting.
    pub fn remove_tray_icon(hwnd: isize) {
        let hwnd = as_hwnd(hwnd);
        let mut nid = NOTIFYICONDATAW::default();
        nid.cbSize = std::mem::size_of::<NOTIFYICONDATAW>() as u32;
        nid.hWnd = hwnd;
        nid.uID = TRAY_ICON_UID;
        unsafe {
            let _ = Shell_NotifyIconW(NOTIFY_ICON_MESSAGE(2), &nid); // NIM_DELETE = 2
        }
    }

    // ── Tray listener (message-only window + pump thread) ─────────────────

    /// Create a hidden message-only window that serves as the callback target
    /// for tray icon notifications and the IPC target for single-instance
    /// communication. Spawns a background thread running `GetMessageW`.
    /// Returns `(hwnd, receiver)`, or `None` on failure.
    pub fn spawn_tray_listener() -> Option<(isize, UnboundedReceiver<TrayEvent>)> {
        let (tx, rx) = mpsc::unbounded::<TrayEvent>();

        // Register a custom "Tn show main" message for cross-instance IPC.
        let msg_show_main =
            unsafe { RegisterWindowMessageW(windows::core::w!("Tn.Terminal.ShowMainWindow.v1")) };

        let hinstance = {
            let hmod = unsafe { GetModuleHandleW(None) }.unwrap_or_default();
            HINSTANCE(hmod.0)
        };

        // Register the window class.
        let class_name = windows::core::w!("Tn.TrayWindow");
        let wc = WNDCLASSW {
            style: CS_HREDRAW | CS_VREDRAW,
            lpfnWndProc: Some(tray_wndproc),
            cbClsExtra: 0,
            cbWndExtra: 0,
            hInstance: hinstance,
            hIcon: HICON::default(),
            hCursor: unsafe { std::mem::zeroed() },
            hbrBackground: unsafe { std::mem::zeroed() },
            lpszMenuName: windows::core::PCWSTR::null(),
            lpszClassName: class_name,
        };
        let atom = unsafe { RegisterClassW(&wc) };
        if atom == 0 {
            // Class might already be registered by a previous (crashed) instance.
            // That's fine — the OS cleans up class registrations on process exit,
            // so only a same-process race could trigger this. Try to proceed.
            tracing::warn!("RegisterClassW for Tn.TrayWindow returned 0 (may already exist)");
        }

        // Create the message-only window.
        let hwnd = unsafe {
            CreateWindowExW(
                Default::default(), // dwExStyle
                class_name,
                windows::core::w!(""), // window name (unused)
                windows::Win32::UI::WindowsAndMessaging::WINDOW_STYLE(0), // style (0 for message-only)
                0,
                0, // x, y
                0,
                0,                  // w, h
                Some(HWND_MESSAGE), // parent = message-only
                None,               // no menu
                Some(hinstance),    // hInstance
                None,               // no extra param
            )
        };
        let hwnd = match hwnd {
            Ok(h) => h,
            Err(e) => {
                tracing::error!("CreateWindowExW for tray window failed: {e:?}");
                return None;
            }
        };

        // Allocate the per-window data and store its pointer in GWLP_USERDATA.
        let data = Box::new(TrayWindowData {
            tx: tx.clone(),
            msg_show_main,
        });
        let data_ptr = Box::into_raw(data);
        unsafe { SetWindowLongPtrW(hwnd, GWLP_USERDATA, data_ptr as isize) };

        let hwnd_value = hwnd.0 as isize;

        // Spawn the message pump thread.
        std::thread::Builder::new()
            .name("tn-tray".into())
            .spawn(move || unsafe {
                let mut msg = MSG::default();
                while GetMessageW(&mut msg, None, 0, 0).0 > 0 {
                    // Messages are dispatched by the wndproc via RegisterClassW
                    // (not TranslateMessage/DispatchMessage — GetMessageW already
                    // dispatched them because we registered the class with a
                    // lpfnWndProc). Actually, we need to dispatch.
                    // Wait — RegisterClassW with lpfnWndProc means GetMessageW
                    // returns messages but does NOT dispatch them. We must call
                    // DispatchMessageW.
                    // Actually, for a message-only window, GetMessageW retrieves
                    // the message; we need DispatchMessageW to call the wndproc.
                    let _ = TranslateMessage(&msg);
                    // Note: TranslateMessage is needed for WM_KEYDOWN→WM_CHAR
                    // translation, which we don't need here, but DispatchMessageW
                    // is the critical one.
                    DispatchMessageW(&msg);
                }
                // If the tx was dropped (GPUI side gone), the sender is dead;
                // the thread exits cleanly.
            })
            .ok();

        Some((hwnd_value, rx))
    }
}

#[cfg(target_os = "windows")]
pub use imp::*;

#[cfg(not(target_os = "windows"))]
mod stub {
    use futures::channel::mpsc::UnboundedReceiver;
    use tn_config::{HotkeySpec, Rect};

    pub fn spawn_hotkey_listener(_spec: &HotkeySpec) -> Option<UnboundedReceiver<()>> {
        None
    }
    pub fn make_topmost(_h: isize) {}
    pub fn set_bounds(_h: isize, _r: Rect) {}
    pub fn set_round_region(_h: isize, _w: f32, _ht: f32, _radius: f32) {}
    pub fn set_ghost_region(_h: isize, _w: f32, _ht: f32, _radius: f32) {}
    pub fn clear_region(_h: isize) {}
    pub fn show(_h: isize, _visible: bool) {}
    pub fn scale_for(_h: isize) -> f32 {
        1.0
    }
    pub fn work_area(_h: isize) -> Option<Rect> {
        None
    }
    pub fn system_beep() {}
    pub fn reduced_motion_enabled() -> bool {
        false
    }
    pub fn install_ime_keyfix(_h: isize) {}
    pub fn set_ime_enabled(_h: isize, _enabled: bool) {}

    // Tray + single-instance stubs.
    #[derive(Clone, Copy, Debug)]
    pub enum TrayEvent {
        Show,
        Quit,
        ShowFromIpc,
    }
    pub static QUITTING: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);
    pub fn create_tray_icon(_hwnd: isize) -> bool {
        false
    }
    pub fn remove_tray_icon(_hwnd: isize) {}
    pub fn spawn_tray_listener() -> Option<(isize, UnboundedReceiver<TrayEvent>)> {
        None
    }
    pub fn probe_hotkey(_spec: &HotkeySpec) -> bool {
        false
    }
    pub fn set_window_icon(_hwnd: isize) {}
}

#[cfg(not(target_os = "windows"))]
pub use stub::*;

/// Extract the OS window handle (HWND, as `isize`) from a gpui [`Window`].
/// gpui's `Window: HasWindowHandle`, so we read the raw handle and unwrap the
/// Win32 variant. `None` on non-Windows or if the handle is unavailable.
pub fn hwnd_of(window: &gpui::Window) -> Option<isize> {
    use raw_window_handle::{HasWindowHandle, RawWindowHandle};
    // gpui's `Window` has an *inherent* `window_handle()` returning its own
    // `AnyWindowHandle`, which shadows the `HasWindowHandle` trait method — call
    // the trait method explicitly to get the raw OS handle.
    let handle = <gpui::Window as HasWindowHandle>::window_handle(window).ok()?;
    match handle.as_raw() {
        RawWindowHandle::Win32(h) => Some(h.hwnd.get()),
        _ => None,
    }
}
